### ISSUE TITLE
Some files showing no relevant lines

### ISSUE THREAD

**Issue by GDYendell** [JoakimSoderberg/coveralls-cmake#18]
Thanks for this, I managed to get it working for my build. However, I find that several files are included, but not found to have any relevant lines. This means they just show as 100% coverage.

Any idea why that might be? ([See repo here](https://github.com/percival-detector/odin-data/pull/1))

**Comment by JoakimSoderberg** [comment]
Hey, not really sure why that happens. And hard to guess without seeing the final file produced:

Looked at your build log here:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/193785882/log.txt

```
...
Generate JSON for file: src/IpcReactor.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/src/appMain.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/DummyPlugin.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/ExcaliburReorderPlugin.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/fileWriterApp.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/FileWriterController.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/PercivalProcessPlugin.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/SharedMemoryController.cpp...
Generate JSON for non-gcov file: /home/travis/build/percival-detector/odin-data/tools/filewriter/SharedMemoryParser.cpp...
Generate final JSON...
###########################################################################
Generated coveralls JSON containing coverage data:
/home/travis/build/percival-detector/odin-data/build/coveralls.json
###########################################################################
[ 50%] Built target coveralls_generate
```

So you could look at this file and maybe see what is different between a file that includes the coverage data properly on coveralls, and these files:
`/home/travis/build/percival-detector/odin-data/build/coveralls.json`

Might be that coveralls simply does that for files that have `null` for the lines. I guess one test you could do is change this line:
https://github.com/percival-detector/odin-data/pull/1/files#diff-3f9c4b26be0d745ae397181c343a025fR451
Change `null` to `0`... At least I think that should be valid. If I'm not mistaken that will tag it as `0` hits, rather than irrelevant (Which coveralls might think means 100% coverage).

Not sure if this has been introduced or always been there... The coveralls team hasn't exactly been responsive and so on. I'd recommend you try http://codecov.io, I prefer that a lot, they even have a plugin for github to get the coverage overlayed in diffs and such. It's a lot simpler to setup.

**Comment by GDYendell** [comment]
Thanks for the quick response! I think you may be right, I will try changing the default to 0.

I will also try out codecov as that does look better, especially if it is easier to set up.

**Comment by hhirsch** [comment]
@GDYendell Did either of those things fix the problem?

**Comment by GDYendell** [comment]
@hhirsch Changing the default from null to 0 did work, however I then got a lot of files with no coverage coming up with 100% coverage (and no relevant lines).

I also decided to try out codecov and I think it is better.
